Add parser for Slovakia
fiboa/cli pull request #121
Opened 2024-11-14 21:24 UTC by ivorbosloper

2024-11-14 21:43 UTC, m-mohr commented on fiboa_cli/datasets/sk.py
> +from ..convert_utils import convert as convert_, download_files
```suggestion
from ..convert_utils import convert as convert_
```

2024-11-14 21:43 UTC, m-mohr commented on fiboa_cli/datasets/sk.py
> +    "https://data.slovensko.sk/download?id=e39ad227-1899-4cff-b7c8-734f90aa0b59&blocksize=0": "HU2024_20240917.zip"
"https://data.slovensko.sk/download?id=e39ad227-1899-4cff-b7c8-734f90aa0b59&blocksize=0": [
        "HU2024_20240917shp/HU2024_20240917.shp"
    ]

2024-11-14 21:43 UTC, m-mohr commented on fiboa_cli/datasets/sk.py
> +
```suggestion
```

2024-11-14 21:43 UTC, m-mohr commented on fiboa_cli/datasets/sk.py
> +        os.path.join(cache, path.replace('.zip', 'shp'), path.replace('.zip', '.shp')),
```suggestion
        SOURCES,
```

2024-11-14 21:44 UTC, m-mohr requested changes
The converter can extract the files for you, see comments.

2024-11-15 08:23 UTC, ivorbosloper commented
Thanks, I wasn't aware of the list-values option for SOURCES . Way better like this. We can merge @m-mohr

2024-11-15 10:11 UTC, m-mohr approved these changes

2024-11-15 10:11 UTC, merged